- thinkerbot/lazydoc
- thinkerbot/constants

# For later...
# - thinkerbot/molecules
# - thinkerbot/external
# - thinkerbot/configurable
# - thinkerbot/shell_test
# - thinkerbot/linecook
# - thinkerbot/gitgo
# - thinkerbot/data_graph
