$:.unshift File.expand_path('../lib', __FILE__)
require 'thinkerbot/site'

logger   = Logger.new($stdout)
logger.datetime_format = "%Y/%m/%d %H:%M:%S"

root_dir = File.expand_path('../..', __FILE__)
site  = Thinkerbot::Site.setup(root_dir, logger)
force = ENV['FORCE'] == 'true'

#
# Site tasks
#

desc 'fetch gems for each project'
task :fetch do
  site.chdir '_project/gems' do
    site.each_release do |release|
      release.fetch(force)
    end
  end
end

desc 'unpack gems for each project'
task :unpack => :fetch do
  site.chdir '_project/gems' do
    site.each_release do |release|
      release.unpack(force)
    end
  end
end

desc 'build rdoc for each project'
task :rdoc => :unpack do
  site.chdir '_project/gems' do
    site.each_release do |release|
      release.build_rdoc(force)
    end
  end
end

desc 'Build site'
task :site => :rdoc do
  site.chdir '.' do
    site.log_sh "jekyll --pygments --safe"
  end
end
task :default => :site
